spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath:sql/user/user_schema.sql
      data-locations: classpath:sql/user/user_data.sql
      encoding: UTF-8
      mode: always

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

  security:
    oauth2.client:
      registration:
        google:
          clientId: '{google client-id}'
          clientSecret: '{google client-secret}'
          scope:
            - email
            - profile
