spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations:
        - classpath:sql/product/product_schema.sql
        - classpath:sql/user/user_schema.sql
        - classpath:sql/user/oauth2_authorized_client.sql
        - classpath:org/springframework/security/oauth2/client/oauth2-client-schema.sql
        - classpath:sql/constraint.sql
      data-locations: classpath:sql/user/user_data.sql
      encoding: UTF-8
      mode: always

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true

  security:
    oauth2.client:
      registration:
        google:
          client-id: ${google.client-id}
          client-secret: ${google.client-secret}
          scope:
            - profile

jwt:
  header: Authorization
  issuer: saiko
  client-secret: ${jwt.token-secret}
  expiry-seconds: 604800000

server:
  port: 80
