-- PK

ALTER TABLE `bidding`
    ADD CONSTRAINT `PK_BIDDING` PRIMARY KEY (`id`);

ALTER TABLE `product`
    ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (`id`);

ALTER TABLE `image`
    ADD CONSTRAINT `PK_IMAGE` PRIMARY KEY (`id`);

ALTER TABLE `permission`
    ADD CONSTRAINT `PK_PERMISSION` PRIMARY KEY (`id`);

ALTER TABLE `group`
    ADD CONSTRAINT `PK_GROUP` PRIMARY KEY (`id`);

ALTER TABLE `group_permission`
    ADD CONSTRAINT `PK_GROUP_PERMISSION` PRIMARY KEY (`id`);

ALTER TABLE `chat_message`
    ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (`id`);

ALTER TABLE `chat_room`
    ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (`id`);

ALTER TABLE `report`
    ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (`id`);

ALTER TABLE `user`
    ADD CONSTRAINT `PK_USER` PRIMARY KEY (`id`);

-- AUTO INCREMENT

ALTER TABLE `bidding`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `report`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `product`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `image`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `chat_message`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `chat_room`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `user`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT FIRST;

-- FK

ALTER TABLE `bidding`
    ADD CONSTRAINT `FK_PRODUCT_ID_FOR_BIDDING`
        FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `bidding`
    ADD CONSTRAINT `FK_USER_ID_FOR_BIDDING`
        FOREIGN KEY (`bidder_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `product`
    ADD CONSTRAINT `FK_USER_ID_FOR_PRODUCT`
        FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `image`
    ADD CONSTRAINT `FK_PRODUCT_ID_FOR_IMAGE`
        FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `group_permission`
    ADD CONSTRAINT `FK_GROUP_ID_FOR_GROUP_PERMISSION`
        FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `group_permission`
    ADD CONSTRAINT `FK_PERMISSION_ID_FOR_GROUP_PERMISSION`
        FOREIGN KEY (`permission_id`) REFERENCES `permission` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `chat_message`
    ADD CONSTRAINT `FK_CHAT_ROOM_ID_FOR_CHAT_MESSAGE`
        FOREIGN KEY (`chat_room_id`) REFERENCES `chat_room` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `chat_message`
    ADD CONSTRAINT `FK_SENDER_ID_FOR_CHAT_MESSAGE`
        FOREIGN KEY (`sender_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `chat_room`
    ADD CONSTRAINT `FK_SELLER_ID_FOR_CHAT_ROOM`
        FOREIGN KEY (`seller_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `chat_room`
    ADD CONSTRAINT `FK_BUYER_ID_FOR_CHAT_ROOM`
        FOREIGN KEY (`buyer_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `user`
    ADD CONSTRAINT `FK_GROUP_ID_FOR_USER`
        FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `report`
    ADD CONSTRAINT `FK_FROM_USER_ID_FOR_REPORT`
        FOREIGN KEY (`from_user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `report`
    ADD CONSTRAINT `FK_TO_USER_ID_FOR_REPORT`
        FOREIGN KEY (`to_user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Unique

ALTER TABLE `group_permission`
    ADD UNIQUE unq_group_id_permission_id (group_id, permission_id);

ALTER TABLE `user`
    ADD UNIQUE unq_provider_and_id (provider, provider_id);

